// Code generated by gen_reg_cs. DO NOT EDIT.
using System;
using GameLogic;
using Pb;
using UnityEngine;

public class MsgReg
{
	[RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterAssembliesLoaded)]
	public static void RegisterAll()
	{
		MsgMeta.RegisterMsgMeta((int)MsgId.C2SHeartbeat, typeof(C2S_Heartbeat));
		MsgMeta.RegisterMsgMeta((int)MsgId.S2CHeartbeat, typeof(S2C_Heartbeat));
		MsgMeta.RegisterMsgMeta((int)MsgId.S2CError, typeof(S2C_Error));
		MsgMeta.RegisterMsgMeta((int)MsgId.C2SLogin, typeof(C2S_Login));
		MsgMeta.RegisterMsgMeta((int)MsgId.S2CLogin, typeof(S2C_Login));
		MsgMeta.RegisterMsgMeta((int)MsgId.C2SGetLevelDetail, typeof(C2S_GetLevelDetail));
		MsgMeta.RegisterMsgMeta((int)MsgId.S2CGetLevelDetail, typeof(S2C_GetLevelDetail));
		MsgMeta.RegisterMsgMeta((int)MsgId.C2SStartLevel, typeof(C2S_StartLevel));
		MsgMeta.RegisterMsgMeta((int)MsgId.S2CStartLevel, typeof(S2C_StartLevel));
		MsgMeta.RegisterMsgMeta((int)MsgId.C2SFinishLevel, typeof(C2S_FinishLevel));
		MsgMeta.RegisterMsgMeta((int)MsgId.S2CFinishLevel, typeof(S2C_FinishLevel));
	}
}
