// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.27.1
// source: game.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgId int32

const (
	MsgId_Unknown            MsgId = 0
	MsgId_c2s_Heartbeat      MsgId = 1
	MsgId_s2c_Heartbeat      MsgId = 2
	MsgId_s2c_Error          MsgId = 3
	MsgId_c2s_Login          MsgId = 100
	MsgId_s2c_Login          MsgId = 101
	MsgId_c2s_GetLevelDetail MsgId = 102
	MsgId_s2c_GetLevelDetail MsgId = 103
	MsgId_c2s_StartLevel     MsgId = 104
	MsgId_s2c_StartLevel     MsgId = 105
	MsgId_c2s_FinishLevel    MsgId = 106
	MsgId_s2c_FinishLevel    MsgId = 107
)

// Enum value maps for MsgId.
var (
	MsgId_name = map[int32]string{
		0:   "Unknown",
		1:   "c2s_Heartbeat",
		2:   "s2c_Heartbeat",
		3:   "s2c_Error",
		100: "c2s_Login",
		101: "s2c_Login",
		102: "c2s_GetLevelDetail",
		103: "s2c_GetLevelDetail",
		104: "c2s_StartLevel",
		105: "s2c_StartLevel",
		106: "c2s_FinishLevel",
		107: "s2c_FinishLevel",
	}
	MsgId_value = map[string]int32{
		"Unknown":            0,
		"c2s_Heartbeat":      1,
		"s2c_Heartbeat":      2,
		"s2c_Error":          3,
		"c2s_Login":          100,
		"s2c_Login":          101,
		"c2s_GetLevelDetail": 102,
		"s2c_GetLevelDetail": 103,
		"c2s_StartLevel":     104,
		"s2c_StartLevel":     105,
		"c2s_FinishLevel":    106,
		"s2c_FinishLevel":    107,
	}
)

func (x MsgId) Enum() *MsgId {
	p := new(MsgId)
	*p = x
	return p
}

func (x MsgId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgId) Descriptor() protoreflect.EnumDescriptor {
	return file_game_proto_enumTypes[0].Descriptor()
}

func (MsgId) Type() protoreflect.EnumType {
	return &file_game_proto_enumTypes[0]
}

func (x MsgId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgId.Descriptor instead.
func (MsgId) EnumDescriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{0}
}

type C2S_Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S_Heartbeat) Reset() {
	*x = C2S_Heartbeat{}
	mi := &file_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_Heartbeat) ProtoMessage() {}

func (x *C2S_Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_Heartbeat.ProtoReflect.Descriptor instead.
func (*C2S_Heartbeat) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{0}
}

type S2C_Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C_Heartbeat) Reset() {
	*x = S2C_Heartbeat{}
	mi := &file_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_Heartbeat) ProtoMessage() {}

func (x *S2C_Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_Heartbeat.ProtoReflect.Descriptor instead.
func (*S2C_Heartbeat) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{1}
}

type S2C_Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrCode                `protobuf:"varint,1,opt,name=Code,proto3,enum=pb.ErrCode" json:"Code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C_Error) Reset() {
	*x = S2C_Error{}
	mi := &file_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_Error) ProtoMessage() {}

func (x *S2C_Error) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_Error.ProtoReflect.Descriptor instead.
func (*S2C_Error) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{2}
}

func (x *S2C_Error) GetCode() ErrCode {
	if x != nil {
		return x.Code
	}
	return ErrCode_Ok
}

type C2S_Login struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoginType     int32                  `protobuf:"varint,1,opt,name=loginType,proto3" json:"loginType,omitempty"` // 0-游客 1-微信 2-抖音
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S_Login) Reset() {
	*x = C2S_Login{}
	mi := &file_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_Login) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_Login) ProtoMessage() {}

func (x *C2S_Login) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_Login.ProtoReflect.Descriptor instead.
func (*C2S_Login) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{3}
}

func (x *C2S_Login) GetLoginType() int32 {
	if x != nil {
		return x.LoginType
	}
	return 0
}

func (x *C2S_Login) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type S2C_Login struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *UserData              `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C_Login) Reset() {
	*x = S2C_Login{}
	mi := &file_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_Login) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_Login) ProtoMessage() {}

func (x *S2C_Login) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_Login.ProtoReflect.Descriptor instead.
func (*S2C_Login) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{4}
}

func (x *S2C_Login) GetData() *UserData {
	if x != nil {
		return x.Data
	}
	return nil
}

type C2S_GetLevelDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         int32                  `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S_GetLevelDetail) Reset() {
	*x = C2S_GetLevelDetail{}
	mi := &file_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_GetLevelDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_GetLevelDetail) ProtoMessage() {}

func (x *C2S_GetLevelDetail) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_GetLevelDetail.ProtoReflect.Descriptor instead.
func (*C2S_GetLevelDetail) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{5}
}

func (x *C2S_GetLevelDetail) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type S2C_GetLevelDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Detail        *LevelDetail           `protobuf:"bytes,1,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C_GetLevelDetail) Reset() {
	*x = S2C_GetLevelDetail{}
	mi := &file_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_GetLevelDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_GetLevelDetail) ProtoMessage() {}

func (x *S2C_GetLevelDetail) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_GetLevelDetail.ProtoReflect.Descriptor instead.
func (*S2C_GetLevelDetail) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{6}
}

func (x *S2C_GetLevelDetail) GetDetail() *LevelDetail {
	if x != nil {
		return x.Detail
	}
	return nil
}

type C2S_StartLevel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         int32                  `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S_StartLevel) Reset() {
	*x = C2S_StartLevel{}
	mi := &file_game_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_StartLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_StartLevel) ProtoMessage() {}

func (x *C2S_StartLevel) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_StartLevel.ProtoReflect.Descriptor instead.
func (*C2S_StartLevel) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{7}
}

func (x *C2S_StartLevel) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type S2C_StartLevel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C_StartLevel) Reset() {
	*x = S2C_StartLevel{}
	mi := &file_game_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_StartLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_StartLevel) ProtoMessage() {}

func (x *S2C_StartLevel) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_StartLevel.ProtoReflect.Descriptor instead.
func (*S2C_StartLevel) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{8}
}

type C2S_FinishLevel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         uint32                 `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S_FinishLevel) Reset() {
	*x = C2S_FinishLevel{}
	mi := &file_game_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_FinishLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_FinishLevel) ProtoMessage() {}

func (x *C2S_FinishLevel) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_FinishLevel.ProtoReflect.Descriptor instead.
func (*C2S_FinishLevel) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{9}
}

func (x *C2S_FinishLevel) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type S2C_FinishLevel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C_FinishLevel) Reset() {
	*x = S2C_FinishLevel{}
	mi := &file_game_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_FinishLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_FinishLevel) ProtoMessage() {}

func (x *S2C_FinishLevel) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_FinishLevel.ProtoReflect.Descriptor instead.
func (*S2C_FinishLevel) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{10}
}

var File_game_proto protoreflect.FileDescriptor

const file_game_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"game.proto\x12\x02pb\x1a\tdef.proto\"\x0f\n" +
	"\rC2S_Heartbeat\"\x0f\n" +
	"\rS2C_Heartbeat\",\n" +
	"\tS2C_Error\x12\x1f\n" +
	"\x04Code\x18\x01 \x01(\x0e2\v.pb.ErrCodeR\x04Code\"=\n" +
	"\tC2S_Login\x12\x1c\n" +
	"\tloginType\x18\x01 \x01(\x05R\tloginType\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"-\n" +
	"\tS2C_Login\x12 \n" +
	"\x04data\x18\x01 \x01(\v2\f.pb.UserDataR\x04data\"*\n" +
	"\x12C2S_GetLevelDetail\x12\x14\n" +
	"\x05level\x18\x01 \x01(\x05R\x05level\"=\n" +
	"\x12S2C_GetLevelDetail\x12'\n" +
	"\x06detail\x18\x01 \x01(\v2\x0f.pb.LevelDetailR\x06detail\"&\n" +
	"\x0eC2S_StartLevel\x12\x14\n" +
	"\x05level\x18\x01 \x01(\x05R\x05level\"\x10\n" +
	"\x0eS2C_StartLevel\"'\n" +
	"\x0fC2S_FinishLevel\x12\x14\n" +
	"\x05level\x18\x01 \x01(\rR\x05level\"\x11\n" +
	"\x0fS2C_FinishLevel*\xe9\x01\n" +
	"\x05MsgId\x12\v\n" +
	"\aUnknown\x10\x00\x12\x11\n" +
	"\rc2s_Heartbeat\x10\x01\x12\x11\n" +
	"\rs2c_Heartbeat\x10\x02\x12\r\n" +
	"\ts2c_Error\x10\x03\x12\r\n" +
	"\tc2s_Login\x10d\x12\r\n" +
	"\ts2c_Login\x10e\x12\x16\n" +
	"\x12c2s_GetLevelDetail\x10f\x12\x16\n" +
	"\x12s2c_GetLevelDetail\x10g\x12\x12\n" +
	"\x0ec2s_StartLevel\x10h\x12\x12\n" +
	"\x0es2c_StartLevel\x10i\x12\x13\n" +
	"\x0fc2s_FinishLevel\x10j\x12\x13\n" +
	"\x0fs2c_FinishLevel\x10kB\x05Z\x03/pbb\x06proto3"

var (
	file_game_proto_rawDescOnce sync.Once
	file_game_proto_rawDescData []byte
)

func file_game_proto_rawDescGZIP() []byte {
	file_game_proto_rawDescOnce.Do(func() {
		file_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)))
	})
	return file_game_proto_rawDescData
}

var file_game_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_game_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_game_proto_goTypes = []any{
	(MsgId)(0),                 // 0: pb.MsgId
	(*C2S_Heartbeat)(nil),      // 1: pb.C2S_Heartbeat
	(*S2C_Heartbeat)(nil),      // 2: pb.S2C_Heartbeat
	(*S2C_Error)(nil),          // 3: pb.S2C_Error
	(*C2S_Login)(nil),          // 4: pb.C2S_Login
	(*S2C_Login)(nil),          // 5: pb.S2C_Login
	(*C2S_GetLevelDetail)(nil), // 6: pb.C2S_GetLevelDetail
	(*S2C_GetLevelDetail)(nil), // 7: pb.S2C_GetLevelDetail
	(*C2S_StartLevel)(nil),     // 8: pb.C2S_StartLevel
	(*S2C_StartLevel)(nil),     // 9: pb.S2C_StartLevel
	(*C2S_FinishLevel)(nil),    // 10: pb.C2S_FinishLevel
	(*S2C_FinishLevel)(nil),    // 11: pb.S2C_FinishLevel
	(ErrCode)(0),               // 12: pb.ErrCode
	(*UserData)(nil),           // 13: pb.UserData
	(*LevelDetail)(nil),        // 14: pb.LevelDetail
}
var file_game_proto_depIdxs = []int32{
	12, // 0: pb.S2C_Error.Code:type_name -> pb.ErrCode
	13, // 1: pb.S2C_Login.data:type_name -> pb.UserData
	14, // 2: pb.S2C_GetLevelDetail.detail:type_name -> pb.LevelDetail
	3,  // [3:3] is the sub-list for method output_type
	3,  // [3:3] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_game_proto_init() }
func file_game_proto_init() {
	if File_game_proto != nil {
		return
	}
	file_def_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_game_proto_goTypes,
		DependencyIndexes: file_game_proto_depIdxs,
		EnumInfos:         file_game_proto_enumTypes,
		MessageInfos:      file_game_proto_msgTypes,
	}.Build()
	File_game_proto = out.File
	file_game_proto_goTypes = nil
	file_game_proto_depIdxs = nil
}
