// Code generated by protoc-gen-autoregister. DO NOT EDIT.
package pb

import (
	"github.com/murang/potato/pb"
	"github.com/murang/potato/pb/vt"
	"reflect"
)

func init() {
	pb.RegisterMsg(uint32(MsgId_c2s_Heartbeat), reflect.TypeOf(&C2S_Heartbeat{}))
	pb.RegisterMsg(uint32(MsgId_s2c_Heartbeat), reflect.TypeOf(&S2C_Heartbeat{}))
	pb.RegisterMsg(uint32(MsgId_s2c_Error), reflect.TypeOf(&S2C_Error{}))
	pb.RegisterMsg(uint32(MsgId_c2s_Login), reflect.TypeOf(&C2S_Login{}))
	pb.RegisterMsg(uint32(MsgId_s2c_Login), reflect.TypeOf(&S2C_Login{}))
	pb.RegisterMsg(uint32(MsgId_c2s_GetLevelDetail), reflect.TypeOf(&C2S_GetLevelDetail{}))
	pb.RegisterMsg(uint32(MsgId_s2c_GetLevelDetail), reflect.TypeOf(&S2C_GetLevelDetail{}))
	pb.RegisterMsg(uint32(MsgId_c2s_StartLevel), reflect.TypeOf(&C2S_StartLevel{}))
	pb.RegisterMsg(uint32(MsgId_s2c_StartLevel), reflect.TypeOf(&S2C_StartLevel{}))
	pb.RegisterMsg(uint32(MsgId_c2s_FinishLevel), reflect.TypeOf(&C2S_FinishLevel{}))
	pb.RegisterMsg(uint32(MsgId_s2c_FinishLevel), reflect.TypeOf(&S2C_FinishLevel{}))
	vt.Register(&C2S_Heartbeat{})
	vt.Register(&S2C_Heartbeat{})
	vt.Register(&S2C_Error{})
	vt.Register(&C2S_Login{})
	vt.Register(&S2C_Login{})
	vt.Register(&C2S_GetLevelDetail{})
	vt.Register(&S2C_GetLevelDetail{})
	vt.Register(&C2S_StartLevel{})
	vt.Register(&S2C_StartLevel{})
	vt.Register(&C2S_FinishLevel{})
	vt.Register(&S2C_FinishLevel{})
}
