
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class Misc : Luban.BeanBase
{
    public Misc(ByteBuf _buf) 
    {
        HpMax = _buf.ReadInt();
        HpRestoreSecond = _buf.ReadInt();
        ScoreStart = _buf.ReadInt();
    }

    public static Misc DeserializeMisc(ByteBuf _buf)
    {
        return new Misc(_buf);
    }

    /// <summary>
    /// 最大体力
    /// </summary>
    public readonly int HpMax;
    /// <summary>
    /// 体力恢复时间
    /// </summary>
    public readonly int HpRestoreSecond;
    /// <summary>
    /// 通关分数起始点
    /// </summary>
    public readonly int ScoreStart;
   
    public const int __ID__ = 2398476;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "hpMax:" + HpMax + ","
        + "hpRestoreSecond:" + HpRestoreSecond + ","
        + "scoreStart:" + ScoreStart + ","
        + "}";
    }
}
}

