
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace GameConfig
{
public partial class Tables
{
    #region The Tables

    private TbMisc m_TbMisc;
    public TbMisc TbMisc 
    {
        get
        {
            if (m_TbMisc == null)
            {
                m_TbMisc = new TbMisc(defaultLoader("tbmisc"));
                m_TbMisc.ResolveRef(this);
            }
            return m_TbMisc;
        }
        set
        {
            m_TbMisc = value;
            m_TbMisc.ResolveRef(this);
        }
    }
    private TbItem m_TbItem;
    public TbItem TbItem 
    {
        get
        {
            if (m_TbItem == null)
            {
                m_TbItem = new TbItem(defaultLoader("tbitem"));
                m_TbItem.ResolveRef(this);
            }
            return m_TbItem;
        }
        set
        {
            m_TbItem = value;
            m_TbItem.ResolveRef(this);
        }
    }

    #endregion

    System.Func<string, ByteBuf> defaultLoader;

    public Tables(System.Func<string, ByteBuf> loader)
    {
        SetDefaultLoader(loader);
        Init();
    }
    
    public void SetDefaultLoader(System.Func<string, ByteBuf> loader)
    {
        defaultLoader = null;
        defaultLoader = loader;
    }

    //public partial void Init();

    public void Init(){}
}

}
