
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public partial class TbMisc
{
    private readonly System.Collections.Generic.Dictionary<int, Misc> _dataMap;
    private readonly System.Collections.Generic.List<Misc> _dataList;
    
    public TbMisc(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, Misc>(n);
        _dataList = new System.Collections.Generic.List<Misc>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Misc _v;
            _v = global::GameConfig.Misc.DeserializeMisc(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.HpRestoreSecond, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Misc> DataMap => _dataMap;
    public System.Collections.Generic.List<Misc> DataList => _dataList;

    public Misc GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Misc Get(int key) => _dataMap[key];
    public Misc this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

