// Code generated by gen_reg_cs. DO NOT EDIT.
using System;
using GameLogic;
using Pb;
using UnityEngine;

public class MsgReg
{
	[RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterAssembliesLoaded)]
	public static void RegisterAll()
	{
		MsgMeta.RegisterMsgMeta((int)MsgId.C2SHello, typeof(C2S_Hello));
		MsgMeta.RegisterMsgMeta((int)MsgId.S2CHello, typeof(S2C_Hello));
	}
}
